version: '2'
services:
  busylight_mqtt:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: busylight_mqtt
    restart: unless-stopped
    privileged: true
    devices:
      - '/dev:/dev'